pull_request_rules:
  - name: automatic merge when all checks pass
    conditions:
      - status-success=code-inspector/violations
      - status-success=code-inspector/duplicates
    actions:
      merge:
        method: merge
